# docker compose 版本
version: "2"
services:
  # zookeeper 容器
  zookeeper_3210:
    image: zookeeper
    ports:
      - 3210:3210
  # dubbo provider 容器
  producer:
    image: 'producer:latest'
    environment:
      - ZOOKEEPER_SERVER=zookeeper
  # dubbo consumer 容器
  consumer:
    image: 'consumer:latest'
    environment:
      - ZOOKEEPER_SERVER=zookeeper
      - SERVER_PORT=8899
    ports:
      - 8899:8899